#!/usr/bin/env python3
"""Merge v1 catalog with supplemental entries into exercise_catalog_v2.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
V1 = ROOT / "app/src/main/assets/catalog/exercise_catalog_v1.json"
OUT = ROOT / "app/src/main/assets/catalog/exercise_catalog_v2.json"

SUPPLEMENT = [
    {"catalogId": "lw:chin-up", "displayName": "Chin-up", "equipment": "bodyweight", "bodyPosition": "standing", "primaryMovement": "pulldown", "gripOrientation": "supinated", "unitType": "bodyweight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}, {"muscle": "biceps_brachii", "role": "synergist", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Hang with underhand grip.", "Pull chin above bar.", "Lower with control."], "comments": ["Keep core tight."], "tags": ["back", "bodyweight"]},
    {"catalogId": "lw:dip", "displayName": "Parallel Bar Dip", "equipment": "bodyweight", "bodyPosition": "standing", "primaryMovement": "bench_press", "unitType": "bodyweight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "triceps_brachii", "role": "target", "displayName": "Triceps Brachii", "bodyRegion": "arms"}, {"muscle": "pectoralis_major_sternal", "role": "synergist", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Support on parallel bars.", "Lower until upper arms are parallel.", "Press back up."], "comments": ["Lean forward to emphasize chest."], "tags": ["chest", "triceps", "bodyweight"]},
    {"catalogId": "lw:front-squat", "displayName": "Barbell Front Squat", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "squat", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "advanced"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Rack bar on front delts.", "Squat down keeping torso upright.", "Drive up through mid-foot."], "comments": ["Elbows high."], "tags": ["legs", "squat"]},
    {"catalogId": "lw:sumo-deadlift", "displayName": "Barbell Sumo Deadlift", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "deadlift", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "gluteus_maximus", "role": "target", "displayName": "Gluteus Maximus", "bodyRegion": "legs"}, {"muscle": "adductors", "role": "synergist", "displayName": "Adductors", "bodyRegion": "legs"}], "instructions": ["Wide stance, toes out.", "Grip bar inside knees.", "Stand by extending hips and knees."], "comments": ["Keep chest up."], "tags": ["hinge", "barbell"]},
    {"catalogId": "lw:pendlay-row", "displayName": "Barbell Pendlay Row", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "row", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}], "instructions": ["Bar on floor each rep.", "Pull to lower chest.", "Return bar to floor."], "comments": ["Explosive concentric, controlled eccentric."], "tags": ["back", "barbell"]},
    {"catalogId": "lw:t-bar-row", "displayName": "T-Bar Row", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "row", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}], "instructions": ["Straddle bar.", "Pull handle to chest.", "Lower under control."], "comments": ["Keep back flat."], "tags": ["back", "barbell"]},
    {"catalogId": "lw:dumbbell-row", "displayName": "Dumbbell Row", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "row", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}], "instructions": ["Support on bench.", "Row dumbbell to hip.", "Lower slowly."], "comments": ["Avoid rotating torso excessively."], "tags": ["back", "dumbbell"]},
    {"catalogId": "lw:dumbbell-bench", "displayName": "Dumbbell Flat Bench Press", "equipment": "dumbbell", "bodyPosition": "flat_bench", "primaryMovement": "bench_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "pectoralis_major_sternal", "role": "target", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Press dumbbells over chest.", "Lower with elbows at ~45°.", "Press to lockout."], "comments": ["Touch dumbbells lightly at top optional."], "tags": ["chest", "dumbbell"]},
    {"catalogId": "lw:dumbbell-shoulder-press", "displayName": "Dumbbell Shoulder Press", "equipment": "dumbbell", "bodyPosition": "seated", "primaryMovement": "overhead_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "anterior_deltoid", "role": "target", "displayName": "Anterior Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Press dumbbells overhead.", "Lower to ear level.", "Repeat."], "comments": ["Do not flare elbows excessively."], "tags": ["shoulders", "dumbbell"]},
    {"catalogId": "lw:arnold-press", "displayName": "Dumbbell Arnold Press", "equipment": "dumbbell", "bodyPosition": "seated", "primaryMovement": "overhead_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "anterior_deltoid", "role": "target", "displayName": "Anterior Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Start palms facing you.", "Rotate and press overhead.", "Reverse on the way down."], "comments": ["Use moderate weight."], "tags": ["shoulders", "dumbbell"]},
    {"catalogId": "lw:rear-delt-fly", "displayName": "Dumbbell Rear Delt Fly", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "fly", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "posterior_deltoid", "role": "target", "displayName": "Posterior Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Hinge forward.", "Raise arms out to sides.", "Squeeze rear delts."], "comments": ["Light weight, high control."], "tags": ["shoulders", "isolation"]},
    {"catalogId": "lw:cable-fly", "displayName": "Cable Chest Fly", "equipment": "cable", "bodyPosition": "standing", "primaryMovement": "fly", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "pectoralis_major_sternal", "role": "target", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Set cables at shoulder height.", "Bring handles together.", "Return with stretch."], "comments": ["Slight bend in elbows."], "tags": ["chest", "cable"]},
    {"catalogId": "lw:pec-deck", "displayName": "Machine Pec Deck Fly", "equipment": "machine", "bodyPosition": "seated", "primaryMovement": "fly", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "pectoralis_major_sternal", "role": "target", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Sit with back on pad.", "Bring pads together.", "Control the return."], "comments": ["Do not overstretch shoulders."], "tags": ["chest", "machine"]},
    {"catalogId": "lw:smith-bench", "displayName": "Smith Machine Bench Press", "equipment": "smith_machine", "bodyPosition": "flat_bench", "primaryMovement": "bench_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "pectoralis_major_sternal", "role": "target", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Set bench under Smith bar.", "Lower to chest and press."], "comments": ["Fixed bar path reduces stabilizer demand."], "tags": ["chest", "smith"]},
    {"catalogId": "lw:smith-squat", "displayName": "Smith Machine Squat", "equipment": "smith_machine", "bodyPosition": "standing", "primaryMovement": "squat", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Bar on upper back.", "Squat to depth.", "Stand up."], "comments": ["Feet slightly forward if needed."], "tags": ["legs", "smith"]},
    {"catalogId": "lw:hack-squat", "displayName": "Machine Hack Squat", "equipment": "machine", "bodyPosition": "standing", "primaryMovement": "squat", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Shoulders under pads.", "Lower sled.", "Press up."], "comments": ["Keep lower back in contact."], "tags": ["legs", "machine"]},
    {"catalogId": "lw:bulgarian-split-squat", "displayName": "Dumbbell Bulgarian Split Squat", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "lunge", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Rear foot elevated.", "Lower until front thigh parallel.", "Drive up."], "comments": ["Keep front knee tracking over foot."], "tags": ["legs", "unilateral"]},
    {"catalogId": "lw:goblet-squat", "displayName": "Dumbbell Goblet Squat", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "squat", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Hold dumbbell at chest.", "Squat between hips.", "Stand tall."], "comments": ["Great beginner squat pattern."], "tags": ["legs", "dumbbell"]},
    {"catalogId": "lw:standing-calf-raise", "displayName": "Standing Calf Raise", "equipment": "machine", "bodyPosition": "standing", "primaryMovement": "raise", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "gastrocnemius", "role": "target", "displayName": "Gastrocnemius", "bodyRegion": "legs"}], "instructions": ["Balls of feet on platform.", "Rise onto toes.", "Lower with stretch."], "comments": ["Pause at top optional."], "tags": ["calves", "machine"]},
    {"catalogId": "lw:seated-calf-raise", "displayName": "Seated Calf Raise", "equipment": "machine", "bodyPosition": "seated", "primaryMovement": "raise", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "soleus", "role": "target", "displayName": "Soleus", "bodyRegion": "legs"}], "instructions": ["Knees under pad.", "Raise heels.", "Lower slowly."], "comments": ["Emphasizes soleus."], "tags": ["calves", "machine"]},
    {"catalogId": "lw:hammer-curl", "displayName": "Dumbbell Hammer Curl", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "curl", "gripOrientation": "neutral", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "brachialis", "role": "target", "displayName": "Brachialis", "bodyRegion": "arms"}, {"muscle": "biceps_brachii", "role": "synergist", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Neutral grip curl.", "Keep elbows fixed.", "Lower under control."], "comments": ["Do not swing."], "tags": ["arms", "biceps"]},
    {"catalogId": "lw:preacher-curl", "displayName": "EZ-Bar Preacher Curl", "equipment": "barbell", "bodyPosition": "seated", "primaryMovement": "curl", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "biceps_brachii", "role": "target", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Arms on preacher pad.", "Curl bar up.", "Lower fully."], "comments": ["Avoid lifting elbows off pad."], "tags": ["arms", "biceps"]},
    {"catalogId": "lw:skull-crusher", "displayName": "EZ-Bar Skull Crusher", "equipment": "barbell", "bodyPosition": "flat_bench", "primaryMovement": "extension", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "triceps_brachii", "role": "target", "displayName": "Triceps Brachii", "bodyRegion": "arms"}], "instructions": ["Lower bar to forehead.", "Extend elbows.", "Keep upper arms vertical."], "comments": ["Use spotter if needed."], "tags": ["arms", "triceps"]},
    {"catalogId": "lw:overhead-tricep-ext", "displayName": "Dumbbell Overhead Triceps Extension", "equipment": "dumbbell", "bodyPosition": "seated", "primaryMovement": "extension", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "triceps_brachii", "role": "target", "displayName": "Triceps Brachii", "bodyRegion": "arms"}], "instructions": ["Press dumbbell overhead.", "Lower behind head.", "Extend arms."], "comments": ["Keep elbows in."], "tags": ["arms", "triceps"]},
    {"catalogId": "lw:close-grip-bench", "displayName": "Close Grip Barbell Bench Press", "equipment": "barbell", "bodyPosition": "flat_bench", "primaryMovement": "bench_press", "gripWidth": "close", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "triceps_brachii", "role": "target", "displayName": "Triceps Brachii", "bodyRegion": "arms"}], "instructions": ["Hands shoulder-width or narrower.", "Lower to lower chest.", "Press up."], "comments": ["Elbows tucked."], "tags": ["arms", "triceps", "barbell"]},
    {"catalogId": "lw:shrug", "displayName": "Barbell Shrug", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "raise", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "trapezius", "role": "target", "displayName": "Trapezius", "bodyRegion": "back"}], "instructions": ["Hold bar at thighs.", "Elevate shoulders.", "Lower slowly."], "comments": ["Do not roll shoulders."], "tags": ["traps", "barbell"]},
    {"catalogId": "lw:upright-row", "displayName": "Barbell Upright Row", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "raise", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "lateral_deltoid", "role": "target", "displayName": "Lateral Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Pull bar along body to chin height.", "Lead with elbows.", "Lower with control."], "comments": ["Use grip width comfortable for shoulders."], "tags": ["shoulders", "barbell"]},
    {"catalogId": "lw:good-morning", "displayName": "Barbell Good Morning", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "deadlift", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "advanced"}, "muscleRoles": [{"muscle": "hamstrings", "role": "target", "displayName": "Hamstrings", "bodyRegion": "legs"}, {"muscle": "erector_spinae", "role": "synergist", "displayName": "Erector Spinae", "bodyRegion": "back"}], "instructions": ["Bar on back.", "Hinge hips back.", "Return to stand."], "comments": ["Start light.", "Maintain neutral spine."], "tags": ["hinge", "hamstrings"]},
    {"catalogId": "lw:glute-bridge", "displayName": "Barbell Glute Bridge", "equipment": "barbell", "bodyPosition": "lying", "primaryMovement": "squat", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "gluteus_maximus", "role": "target", "displayName": "Gluteus Maximus", "bodyRegion": "legs"}], "instructions": ["Bar over hips.", "Drive hips up.", "Squeeze glutes at top."], "comments": ["Use pad on hips."], "tags": ["glutes", "barbell"]},
    {"catalogId": "lw:cable-crunch", "displayName": "Cable Kneeling Crunch", "equipment": "cable", "bodyPosition": "kneeling", "primaryMovement": "curl", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "rectus_abdominis", "role": "target", "displayName": "Rectus Abdominis", "bodyRegion": "core"}], "instructions": ["Kneel facing cable.", "Crunch down using abs.", "Return with control."], "comments": ["Do not pull with arms."], "tags": ["core", "cable"]},
    {"catalogId": "lw:hanging-leg-raise", "displayName": "Hanging Leg Raise", "equipment": "bodyweight", "bodyPosition": "standing", "primaryMovement": "raise", "unitType": "bodyweight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "rectus_abdominis", "role": "target", "displayName": "Rectus Abdominis", "bodyRegion": "core"}], "instructions": ["Hang from bar.", "Raise legs to parallel or higher.", "Lower without swinging."], "comments": ["Bend knees to regress."], "tags": ["core", "bodyweight"]},
    {"catalogId": "lw:plank", "displayName": "Front Plank", "equipment": "bodyweight", "bodyPosition": "lying", "primaryMovement": "raise", "unitType": "time", "classification": {"mechanics": "isolated", "force": "static", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "rectus_abdominis", "role": "target", "displayName": "Rectus Abdominis", "bodyRegion": "core"}], "instructions": ["Forearms and toes on floor.", "Hold body straight.", "Breathe steadily."], "comments": ["Squeeze glutes."], "tags": ["core", "bodyweight"]},
    {"catalogId": "lw:kettlebell-swing", "displayName": "Kettlebell Swing", "equipment": "kettlebell", "bodyPosition": "standing", "primaryMovement": "deadlift", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "gluteus_maximus", "role": "target", "displayName": "Gluteus Maximus", "bodyRegion": "legs"}, {"muscle": "hamstrings", "role": "synergist", "displayName": "Hamstrings", "bodyRegion": "legs"}], "instructions": ["Hinge and hike kettlebell.", "Drive hips to swing to chest height.", "Let bell float down."], "comments": ["Power from hips, not arms."], "tags": ["hinge", "kettlebell"]},
    {"catalogId": "lw:farmer-carry", "displayName": "Dumbbell Farmer Carry", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "carry", "unitType": "weight", "classification": {"mechanics": "compound", "force": "static", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "forearms", "role": "target", "displayName": "Forearms", "bodyRegion": "arms"}, {"muscle": "trapezius", "role": "stabilizer", "displayName": "Trapezius", "bodyRegion": "back"}], "instructions": ["Hold heavy dumbbells at sides.", "Walk with tall posture.", "Maintain grip."], "comments": ["Short quick steps."], "tags": ["carry", "dumbbell"]},
    {"catalogId": "lw:reverse-fly-machine", "displayName": "Machine Reverse Fly", "equipment": "machine", "bodyPosition": "seated", "primaryMovement": "fly", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "posterior_deltoid", "role": "target", "displayName": "Posterior Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Sit facing pad.", "Open arms against resistance.", "Squeeze rear delts."], "comments": ["Control the negative."], "tags": ["shoulders", "machine"]},
    {"catalogId": "lw:decline-bench", "displayName": "Barbell Decline Bench Press", "equipment": "barbell", "bodyPosition": "decline", "primaryMovement": "bench_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "intermediate"}, "muscleRoles": [{"muscle": "pectoralis_major_sternal", "role": "target", "displayName": "Pectoralis Major (Sternal)", "bodyRegion": "chest"}], "instructions": ["Secure legs on decline bench.", "Lower bar to lower chest.", "Press up."], "comments": ["Use spotter."], "tags": ["chest", "barbell"]},
    {"catalogId": "lw:wide-grip-pulldown", "displayName": "Wide Grip Lat Pulldown", "equipment": "cable", "bodyPosition": "seated", "primaryMovement": "pulldown", "gripWidth": "wide", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}], "instructions": ["Wide overhand grip.", "Pull bar to upper chest.", "Control return."], "comments": ["Lean slightly back."], "tags": ["back", "cable"]},
    {"catalogId": "lw:straight-arm-pulldown", "displayName": "Cable Straight Arm Pulldown", "equipment": "cable", "bodyPosition": "standing", "primaryMovement": "pulldown", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}], "instructions": ["Arms straight.", "Pull bar to thighs.", "Return slowly."], "comments": ["Minimal elbow bend."], "tags": ["back", "cable", "isolation"]},
    {"catalogId": "lw:ez-bar-curl", "displayName": "EZ-Bar Curl", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "curl", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "biceps_brachii", "role": "target", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Curl EZ-bar up.", "Lower under control."], "comments": ["Wrist-friendly grip."], "tags": ["arms", "biceps"]},
    {"catalogId": "lw:cable-curl", "displayName": "Cable Biceps Curl", "equipment": "cable", "bodyPosition": "standing", "primaryMovement": "curl", "unitType": "weight", "classification": {"mechanics": "isolated", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "biceps_brachii", "role": "target", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Curl handle up.", "Squeeze at top.", "Lower slowly."], "comments": ["Constant tension."], "tags": ["arms", "biceps", "cable"]},
    {"catalogId": "lw:reverse-grip-row", "displayName": "Cable Reverse Grip Row", "equipment": "cable", "bodyPosition": "seated", "primaryMovement": "row", "gripOrientation": "supinated", "unitType": "weight", "classification": {"mechanics": "compound", "force": "pull", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "latissimus_dorsi", "role": "target", "displayName": "Latissimus Dorsi", "bodyRegion": "back"}, {"muscle": "biceps_brachii", "role": "synergist", "displayName": "Biceps Brachii", "bodyRegion": "arms"}], "instructions": ["Underhand grip on handle.", "Row to abdomen.", "Extend arms."], "comments": ["Emphasizes lower lats."], "tags": ["back", "cable"]},
    {"catalogId": "lw:landmine-press", "displayName": "Landmine Press", "equipment": "barbell", "bodyPosition": "standing", "primaryMovement": "overhead_press", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "anterior_deltoid", "role": "target", "displayName": "Anterior Deltoid", "bodyRegion": "shoulders"}], "instructions": ["Hold end of barbell.", "Press up and forward.", "Lower under control."], "comments": ["Shoulder-friendly angle."], "tags": ["shoulders", "barbell"]},
    {"catalogId": "lw:step-up", "displayName": "Dumbbell Step-up", "equipment": "dumbbell", "bodyPosition": "standing", "primaryMovement": "lunge", "unitType": "weight", "classification": {"mechanics": "compound", "force": "push", "difficulty": "beginner"}, "muscleRoles": [{"muscle": "quadriceps", "role": "target", "displayName": "Quadriceps", "bodyRegion": "legs"}], "instructions": ["Step onto box.", "Drive through lead leg.", "Control descent."], "comments": ["Use appropriate box height."], "tags": ["legs", "unilateral"]},
]

def normalize(entry: dict) -> dict:
    base = {
        "namingMode": "structured",
        "instructions": entry.get("instructions", []),
        "comments": entry.get("comments", []),
        "tags": entry.get("tags", []),
    }
    merged = {**entry, **base}
    if "classification" in merged:
        c = merged["classification"]
        if "exrxCategoryPath" not in c:
            c["exrxCategoryPath"] = []
        merged["classification"] = c
    return merged

def main():
    v1 = json.loads(V1.read_text(encoding="utf-8"))
    existing_ids = {e["catalogId"] for e in v1["entries"]}
    merged_entries = list(v1["entries"])
    for raw in SUPPLEMENT:
        e = normalize(raw)
        if e["catalogId"] not in existing_ids:
            merged_entries.append(e)
            existing_ids.add(e["catalogId"])
    out = {
        "catalogVersion": 2,
        "sourceAttribution": v1["sourceAttribution"],
        "entries": merged_entries,
    }
    OUT.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote {len(merged_entries)} entries to {OUT}")

if __name__ == "__main__":
    main()
